const MINDUSTRY_LIQUIDS = ['cryofluid', 'oil', 'slag', 'water'];

const MINDUSTRY_ITEMS = [
  'blast-compound',
  'coal',
  'copper',
  'graphite',
  'lead',
  'metaglass',
  'phase-fabric',
  'plastanium',
  'pyratite',
  'sand',
  'scrap',
  'silicon',
  'spore-pod',
  'surge-alloy',
  'thorium',
  'titanium',
];

const MINDUSTRY_LOOKUP_TARGETS = ['block', 'unit', 'item', 'liquid'].map(t => [
  t,
  t,
]);

const MINDUSTRY_SELF = ['counter', 'links', 'this', 'time', 'unit'];

const MINDUSTRY_ACCESS = [
  'ammo',
  'ammoCapacity',
  'boosting',
  'building',
  'buildx',
  'buildy',
  'commanded',
  'config',
  'controlled',
  'controller',
  'dead',
  'efficiency',
  'enabled',
  'firstItem',
  'flag',
  'health',
  'heat',
  'itemCapacity',
  'liquidCapacity',
  'maxHealth',
  'maxUnits',
  'mineX',
  'mineY',
  'mining',
  'name',
  'payloadCount',
  'payloadType',
  'powerCapacity',
  'powerNetCapacity',
  'powerNetIn',
  'powerNetOut',
  'powerNetStored',
  'progress',
  'range',
  'rotation',
  'selectedBlock',
  'selectedRotation',
  'shootX',
  'shootY',
  'shooting',
  'size',
  'team',
  'timescale',
  'totalItems',
  'totalLiquids',
  'totalPower',
  'type',
  'x',
  'y',
];

const MINDUSTRY_BLOCKS = {
  crafting: [
    'blast-mixer',
    'coal-centrifuge',
    'cryofluid-mixer',
    'disassembler',
    'graphite-press',
    'incinerator',
    'kiln',
    'melter',
    'multi-press',
    'phase-weaver',
    'plastanium-compressor',
    'pulverizer',
    'pyratite-mixer',
    'separator',
    'silicon-crucible',
    'silicon-smelter',
    'spore-press',
    'surge-smelter',
  ],

  sandbox: [
    'illuminator',
    'item-source',
    'item-void',
    'liquid-source',
    'liquid-void',
    'power-source',
    'power-void',
  ],

  defense: [
    'copper-wall-large',
    'copper-wall',
    'door-large',
    'door',
    'force-projector',
    'mend-projector',
    'mender',
    'overdrive-dome',
    'overdrive-projector',
    'phase-wall-large',
    'phase-wall',
    'plastanium-wall-large',
    'plastanium-wall',
    'scrap-wall-gigantic',
    'scrap-wall-huge',
    'scrap-wall-large',
    'scrap-wall',
    'shock-mine',
    'surge-wall-large',
    'surge-wall',
    'thorium-wall-large',
    'thorium-wall',
    'thruster',
    'titanium-wall-large',
    'titanium-wall',
  ],

  transport: [
    'armored-conveyor',
    'conveyor',
    'distributor',
    'inverted-sorter',
    'item-bridge',
    'junction',
    'mass-driver',
    'overflow-gate',
    'payload-conveyor',
    'payload-router',
    'phase-conveyor',
    'plastanium-conveyor',
    'router',
    'sorter',
    'titanium-conveyor',
    'underflow-gate',
  ],

  liquid: [
    'bridge-conduit',
    'conduit',
    'liquid-junction',
    'liquid-router',
    'liquid-tank',
    'mechanical-pump',
    'phase-conduit',
    'plated-conduit',
    'pulse-conduit',
    'rotary-pump',
    'thermal-pump',
  ],

  power: [
    'battery-large',
    'battery',
    'combustion-generator',
    'differential-generator',
    'diode',
    'impact-reactor',
    'large-solar-panel',
    'power-node-large',
    'power-node',
    'rtg-generator',
    'solar-panel',
    'steam-generator',
    'surge-tower',
    'thermal-generator',
    'thorium-reactor',
  ],

  production: [
    'blast-drill',
    'cultivator',
    'laser-drill',
    'mechanical-drill',
    'oil-extractor',
    'pneumatic-drill',
    'water-extractor',
  ],

  storage: [
    'container',
    'core-foundation',
    'core-nucleus',
    'core-shard',
    'unloader',
    'vault',
  ],

  turrets: [
    'arc',
    'cyclone',
    'duo',
    'foreshadow',
    'fuse',
    'hail',
    'lancer',
    'meltdown',
    'parallax',
    'ripple',
    'salvo',
    'scatter',
    'scorch',
    'segment',
    'spectre',
    'swarmer',
    'tsunami',
    'wave',
  ],

  units: [
    'additive-reconstructor',
    'air-factory',
    'command-center',
    'exponential-reconstructor',
    'ground-factory',
    'multiplicative-reconstructor',
    'naval-factory',
    'repair-point',
    'resupply-point',
    'tetrative-reconstructor',
  ],

  logic: [
    'hyper-processor',
    'large-logic-display',
    'logic-display',
    'logic-processor',
    'memory-bank',
    'memory-cell',
    'message',
    'micro-processor',
    'switch-block',
  ],

  campaign: ['launch-pad', 'launch-pad-large', 'interplanetary-accelerator'],
};

const MINDUSTRY_UNITS = [
  'alpha',
  'antumbra',
  'arkyid',
  'atrax',
  'beta',
  'block',
  'bryde',
  'corvus',
  'crawler',
  'dagger',
  'eclipse',
  'flare',
  'fortress',
  'gamma',
  'horizon',
  'mace',
  'mega',
  'minke',
  'mono',
  'nova',
  'oct',
  'omura',
  'poly',
  'pulsar',
  'quad',
  'quasar',
  'reign',
  'risso',
  'scepter',
  'sei',
  'spiroct',
  'toxopid',
  'vela',
  'zenith',
];

const MINDUSTRY_CONTROL_TARGETS = [
  'enabled',
  'configure',
  'shoot',
  'shootp',
  'color',
].map(t => [t, t]);

const MINDUSTRY_RADAR_TARGETS = [
  'ally',
  'any',
  'attacker',
  'boss',
  'enemy',
  'flying',
  'ground',
  'player',
].map(t => [t, t]);

const MINDUSTRY_RADAR_SORTS = [
  'armor',
  'distance',
  'health',
  'maxHealth',
  'shield',
].map(t => [t, t]);

const MINDUSTRY_LOCATE_BUILDINGS = [
  'battery',
  'core',
  'extinguisher',
  'factory',
  'generator',
  'rally',
  'reactor',
  'repair',
  'resupply',
  'storage',
  'turret',
  'unitModifier',
];

const MINDUSTRY_UNIT_CONTROL = {
  stop: [],
  unbind: [],
  move: ['x', 'y'],
  flag: ['value'],
  approach: ['x', 'y', 'radius'],
  target: ['x', 'y', 'shoot'],
  targetp: ['unit', 'shoot'],
  itemDrop: ['to', 'amount'],
  itemTake: ['from', 'item', 'amount'],
  mine: ['x', 'y'],
  build: ['x', 'y', 'block', 'rotation', 'config'],
  getBlock: ['x', 'y', 'type', 'building'],
  pathfind: [],
  boost: ['enable'],
  payDrop: [],
  payEnter: [],
  payTake: ['takeUnits'],
  within: ['x', 'y', 'radius', 'result'],
};

const MINDUSTRY_DRAW_OPS = {
  clear: ['r', 'g', 'b'],
  color: ['r', 'g', 'b', 'a'],
  stroke: [''],
  line: ['x', 'y', 'x2', 'y2'],
  rect: ['x', 'y', 'width', 'height'],
  poly: ['x', 'y', 'sides', 'radius', 'rotation'],
  lineRect: ['x', 'y', 'width', 'height'],
  linePoly: ['x', 'y', 'sides', 'radius', 'rotation'],
  triangle: ['x', 'y', 'x2', 'y2', 'x3', 'y3'],
  image: ['x', 'y', 'image', 'size', 'rotation'],
};

const MINDUSTRY_JUMP_OPS = [
  ['==', 'equal'],
  ['===', 'strictEqual'],
  ['not', 'notEqual'],
  ['<', 'lessThan'],
  ['<=', 'lessThanEq'],
  ['>', 'greaterThan'],
  ['>=', 'greaterThanEq'],
];

const JUMPABLE_OPS = [
  'equal',
  'strictEqual',
  'notEqual',
  'lessThan',
  'lessThanEq',
  'greaterThan',
  'greaterThanEq',
];

const MINDUSTRY_BINARY_OPS = [
  ['+', 'add'],
  ['-', 'sub'],
  ['*', 'mul'],
  ['/', 'div'],
  ['//', 'idiv'],
  ['%', 'mod'],
  ['%%', 'emod'],
  ['^', 'pow'],

  ['and', 'land'],
  ['not', 'notEqual'],
  ['==', 'equal'],
  ['===', 'strictEqual'],

  ['<', 'lessThan'],
  ['<=', 'lessThanEq'],
  ['>', 'greaterThan'],
  ['>=', 'greaterThanEq'],

  ['<<', 'shl'],
  ['>>', 'shr'],
  ['>>>', 'ushr'],
  ['or', 'or'],
  ['b-and', 'and'],
  ['xor', 'xor'],

  ['min', 'min'],
  ['max', 'max'],

  ['angle', 'angle'],
  ['anglediff', 'angleDiff'],
  ['len', 'len'],

  ['noise', 'noise'],
  ['logn', 'logn'],
];

const MINDUSTRY_UNARY_OPS = [
  ['floor', 'floor'],
  ['ceil', 'ceil'],
  ['abs', 'abs'],
  ['sign', 'sign'],
  ['sqrt', 'sqrt'],
  ['rand', 'rand'],
  ['sin', 'sin'],
  ['asin', 'asin'],
  ['cos', 'cos'],
  ['acos', 'acos'],
  ['tan', 'tan'],
  ['atan', 'atan'],
  ['round', 'round'],
  ['log', 'log'],
  ['log10', 'log10'],
  ['flip', 'not'],
];

// Icon sprites from https://github.com/Anuken/Mindustry/tree/master/core/assets-raw/sprites
const SPRITE_BASE =
  'https://raw.githubusercontent.com/Anuken/Mindustry/master/core/assets-raw/sprites';

const ICON_URL = {
  item: name => `${SPRITE_BASE}/items/item-${name}.png`,
  liquid: name => `${SPRITE_BASE}/items/liquid-${name}.png`,
  unit: name => `${SPRITE_BASE}/units/${name}.png`,
};

